### ISSUE TITLE
Binky 

### ISSUE THREAD

**Issue by Wolffy00** [kevinakasam/ERCF_Filament_Cutter#1]
Encoder slotted wheel and push tool are missing,or link to original binky

**Comment by BioCookieYT** [comment]
Hi, since the wheel and the push tool haven't changed with the adaption it isn't worth including them into our cutter repo. You can find the original Binky [here](https://github.com/mneuhaus/EnragedRabbitProject/tree/main/usermods/Binky/STL) ^^
