### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by sanpedrox2** [kevinakasam/ERCF_Filament_Cutter#10]
Great work :)

i built one for my ercf v1 and it went from being an unrealiable mess to more or less 100% reliable after installing the cutter.
the biggest problem i had was forming consistent tips, wich now is less important.

i did have to tweak the servo arm a bit though, the gear didnt quite reach the cutter arm gear and would sometimes skip gears.
so i extended the gear by 1mm out from the arm. now they lock nicely together.

probably my printer tolerances fault though, or the fact i printed it in petg maybe.

really nice work on this, thanks a bunch! :)

**Comment by BioCookieYT** [comment]
Thanks a lot for the feedback!
You are not the only one who has the problem with the gears, it should be fixed with Beta6 which releases soon.
