### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Tutankamon00** [kevinakasam/ERCF_Filament_Cutter#12]
Hi Pease modify a little the design, make the teeth of servo arm wider, to maximize the contact surface with cutter arm, this increase the stability and the durability :)

![immagine](https://github.com/kevinakasam/ERCF_Filament_Cutter/assets/142754987/8300c0ef-18d0-4ed7-9459-7f1cedf18a66)

**Comment by 24Tigger24** [comment]
I haven't tried it yet
[Wider Servo Arm.zip](https://github.com/kevinakasam/ERCF_Filament_Cutter/files/14396845/Wider.Servo.Arm.zip)

**Comment by Tutankamon00** [comment]
> I haven't tried it yet [Wider Servo Arm.zip](https://github.com/kevinakasam/ERCF_Filament_Cutter/files/14396845/Wider.Servo.Arm.zip)

Nice thank you, i'm try to adapt for ercf 1.1 with binky, if is possibile at least only for cutter_arm and servo arm you can share .f3d with history, because this new teeth design is very difficulty to make mod without history, thank you very much

**Comment by Tutankamon00** [comment]
i checked the step of wider servo arm, but you have make it wider in the wrong direction 
![immagine](https://github.com/kevinakasam/ERCF_Filament_Cutter/assets/142754987/32792cb0-d3ee-4662-912e-40cb3baa9f23)

**Comment by 24Tigger24** [comment]
the cutter arm in your CAD is in the wrong position. You have to move it down.

My v1.1 ERCF in CAD: 
[my ERCF v1.1.zip](https://github.com/kevinakasam/ERCF_Filament_Cutter/files/14397229/my.ERCF.v1.1.zip)
(.f3d-file is to large for github)

**Comment by Tutankamon00** [comment]
> the cutter arm in your CAD is in the wrong position. You have to move it down.
> 
> My v1.1 ERCF in CAD: [my ERCF v1.1.zip](https://github.com/kevinakasam/ERCF_Filament_Cutter/files/14397229/my.ERCF.v1.1.zip) (.f3d-file is to large for github)

YES you are right, i have to move down, thank you very much

**Comment by BioCookieYT** [comment]
See Beta7 ;)
