### ISSUE TITLE
Not an issue :-) Just an FYI and some thoughts

### ISSUE THREAD

**Issue by moggieuk** [kevinakasam/ERCF_Filament_Cutter#14]
I love the rework of this design for ERCFv2!  Just letting you know that I'm proposing to add the basic macro support for this into Happy Hare v2.5.0 release .    I'll send a DM on how to access a preview of that release.

Note that I have changed the arrangement of pre-canned macros with HH.  This would require just a little update to your doc (I have added explanation in the v2.5.0 release cfg...)

Also, and this is a little hush hush we are working with some MCU board builders to have two servos by default!  This will make this even easier to support.

Few recommendations and thoughts:
- Use `_MMU_STEP_MOVE ...` instead of `MMU_TEST_MOVE ...`.  They achieve the same thing but the former is the correct way to include in "sequence" macros and will omit debugging output
- Use the INTERVAL option to the mmu_servo ... alleviates the need to turn servo off and eliminates chance of kickback
- Not sure that the `G4 P0` are necessary
- On the idea of a "blocked" homing step.... 
  - The encoder is always prone to 1-2mm of error, but if an MMU had a gate sensor then this would be closer to 0.5mm
  - Trying to detect the blade in the blocked position would likely add a lot of unreliability IMHO. The "collision" detection of extruder in HH is really a hack..
  - I wonder if the inaccuracies you see could be improved by not releasing the ERCF servo until after the cut.  I believe now it will release before the _MMU_STEP_MOVE (or MMU_TEST_MOVE) cause it to go down again.  I can probably safely make the servo up after the POST_UNLOAD macro runs... let me know

Can't wait to try...

**Comment by moggieuk** [comment]
Proposed macro rework:

[mmu_erec_cutter.txt](https://github.com/kevinakasam/ERCF_Filament_Cutter/files/14333992/mmu_erec_cutter.txt)

**Comment by BioCookieYT** [comment]
Thanks again for your help <3
