### ISSUE TITLE
Servo issues and Blade mount

### ISSUE THREAD

**Issue by PaulMellor** [kevinakasam/ERCF_Filament_Cutter#17]
Unsure if it is just my setup or the servo, but it seems that the open and closed servo positions are reversed. When the current implemntation via HH it seems that I have a few issues, firstly when I power on the printer, the serve is locked in position against the arm/bracket causing it to heat up and get extremely warm.
Second issue not sure if it is the HH or the changes bade to the design, but it seems that the when I run the open or closed positions they are operate to where it should be.

**Comment by iamnotahippy** [comment]
Could you upload or paste your mmu_erec_cutter.cfg?
