### ISSUE TITLE
movable blade attachment

### ISSUE THREAD

**Issue by dru0** [kevinakasam/ERCF_Filament_Cutter#19]
The blade is too shallow, after the first use it shifts and does not cut properly. I suggest adding a m3 screw at the bottom instead of the m2 screw and a deeper recess. At mine I did so and now it works correctly.
![image](https://github.com/kevinakasam/ERCF_Filament_Cutter/assets/7027505/06ea0f31-e7c6-4459-a5ca-9aa118415767)

**Comment by BioCookieYT** [comment]
Good idea!

Some of our testers used some M2 heat inserts to secure the knife better, an M3 screw might be better.

**Comment by BioCookieYT** [comment]
See Beta7 ;)
