### ISSUE TITLE
Servo Hinge missing clearance

### ISSUE THREAD

**Issue by mobilemcclintic** [kevinakasam/ERCF_Filament_Cutter#2]
The servo hinge piece on B5 is missing a clearance cutout for the slide bearing stop(?).  This forces one side of the servo hinge to bend around it.
![servo-hinge-missing-clearance](https://github.com/kevinakasam/ERCF_Filament_Cutter/assets/47824980/a6791d48-d1ee-4cfb-8b91-e8d1f5cc4a69)

**Comment by juliusjj25** [comment]
Ran into this same issue, created a part with clearance. 
[Servo_Hinge_Mod.zip](https://github.com/kevinakasam/ERCF_Filament_Cutter/files/13417989/Servo_Hinge_Mod.zip)

**Comment by BioCookieYT** [comment]
Hi,
sorry for the late response and thanks for the feedback, I already opened a branch for this issue, going to work on a solution for this in a bit.

**Comment by BioCookieYT** [comment]
Fixed with commit [58bf14c](https://github.com/kevinakasam/ERCF_Filament_Cutter/commit/58bf14c38e6058d93c8e38f4ddca13f30d7998c8) 
![image](https://github.com/kevinakasam/ERCF_Filament_Cutter/assets/63932294/d8315c37-1543-4f93-9974-175df9de9c9b)
