### ISSUE TITLE
Gear movment

### ISSUE THREAD

**Issue by rufinus** [kevinakasam/ERCF_Filament_Cutter#23]
Please see this little movie: https://photos.app.goo.gl/gbCXH4ThvoQybWH8A
(yes, video doesnt have sound)

after only one cut the lever changes positions - and the angles no longer match.  on the pass through position there is play between the gears, and the gears itself can skip over.

What did i do wrong? Any hints or pointers?

TIA

**Comment by ntchris** [comment]
servo  and two gears initial position/install position need adjust.
also the cut_open cut_close angle need adjust.

**Comment by BioCookieYT** [comment]
Could you please try Beta7? I'm closing this issue now, reopen if the issue persists
