### ISSUE TITLE
beta6 Helical gear angle change to opposite direction to cut better?

### ISSUE THREAD

**Issue by ntchris** [kevinakasam/ERCF_Filament_Cutter#26]
beta6 use helical gear which is great, 
however per my understanding, with current design, the helical gear's angle in this direction(purple color), the cutter arm moves not only to one direction to cut, but also it tends to move outward away from the encoder wall by the axial force pointing outward away (away from encoder wall), therefore the filament is pulled out and has some chance not to cut properly.
If we could change the angle of the gear to opposite direction (green color), the cutter arm shall push inward to the encoder wall therefore the filament shall cut better.
I'm not 100% sure my understanding of the direction is correct thought, seems like it...
 
 
![helical_gear](https://github.com/kevinakasam/ERCF_Filament_Cutter/assets/15345990/9c30a16e-efec-4f99-8491-a36c00f2ca03)

**Comment by BioCookieYT** [comment]
I did it a bit different now with Beta7 ;)
