### ISSUE TITLE
future feature consideration: to cut filament with 45degree or sharper

### ISSUE THREAD

**Issue by ntchris** [kevinakasam/ERCF_Filament_Cutter#27]
future feature consideration: to cut filament with 45degree or sharper
by no means this is an easy task, probably need redesign everything from scratch.

Is it possible to cut with an angle, 45degree or sharper?
So filament can have a sharp head or tip...

maybe it's too difficult for current design.
maybe need using two servos...? One for rotation to align holes and tube, 
the other one for pushing down a cut button and knife...
very difficult design
easy for a manual 45degree cutter, but very difficult for an automatic one...which require two types of movement

**Comment by BioCookieYT** [comment]
It's pretty difficult to achieve this, we already thought about this during Beta4!
Maybe with Beta8....
