### ISSUE TITLE
Holes M3 inserts

### ISSUE THREAD

**Issue by Soprano80** [kevinakasam/ERCF_Filament_Cutter#30]
The M3 heat set inserts holes on the encoder are too big. The holes have a diameter of 4.7 mm. My M3 heat inserts have a diameter of 4.45 mm. This means that the M3 heat set inserts fall into the holes.

**Comment by iamnotahippy** [comment]
Voron standards call for m3 heat set inserts with a length of 4mm and a diameter of 5mm. You need to purchase the proper sized inserts.
