### ISSUE TITLE
Cutter Arm mod

### ISSUE THREAD

**Issue by Tutankamon00** [kevinakasam/ERCF_Filament_Cutter#6]
Hi, i suggest to modify the cutter arm like this, to incorporate the blade...
![immagine](https://github.com/kevinakasam/ERCF_Filament_Cutter/assets/142754987/e62a98ca-c702-4326-afb5-40f256869219)

**Comment by kevinakasam** [comment]
How would it cut the filament if the blade part that cuts the filament is cut out/missing 🤔

**Comment by Tutankamon00** [comment]
> How would it cut the filament if the blade part that cuts the filament is cut out/missing 🤔

i using it from 10 days and work, the blade part is not missing: 
![immagine](https://github.com/kevinakasam/ERCF_Filament_Cutter/assets/142754987/abe3c6d2-73d1-41ff-b448-f84d85dca038)

**Comment by cedbossneo** [comment]
We should also incorporate a clearance for the tube, sometimes the filament blocks on the borders of it

**Comment by sanpedrox2** [comment]
Stl? 😘

**Comment by Tutankamon00** [comment]
> Stl? 😘

[cutterarm.zip](https://github.com/kevinakasam/ERCF_Filament_Cutter/files/14145081/cutterarm.zip)

**Comment by sanpedrox2** [comment]
Nice!
Thanks mate :)

**Comment by Tutankamon00** [comment]
> We should also incorporate a clearance for the tube, sometimes the filament blocks on the borders of it

Hi, please show your mod thx :)

**Comment by BioCookieYT** [comment]
Thanks for the suggestion, your mod found the way in the new Beta6. Still have to update the Readme a bit and give some credits :p
