### ISSUE TITLE
Filament stuck

### ISSUE THREAD

**Issue by tutankino** [kevinakasam/ERCF_Filament_Cutter#7]
Hi, some time if Blade not cut the filament go down the Blade, because Blade arm with force go up , It Need a more robust design for cutter arm movement
![IMG_20240105_212000](https://github.com/kevinakasam/ERCF_Filament_Cutter/assets/134683899/2a53cf47-8ebf-45b9-bb40-1455024664e6)

**Comment by BioCookieYT** [comment]
Hi!
Sorry for the late answer, we are already working on a more robust design on the discord server. KevinAkaSam had the time to try out a bearing version of the cutter, theoretically it would work better but we have to find a better way to mount the bearing. Even with the tightest press fit the bearing slides out after some time.
Could I ask you what Filament you tried cutting? Softer materials should work with the current design.

**Comment by Tutankamon00** [comment]
I use pla+ sunlu and normal pla, with pla+ less problem, is bit soft compared to normal pla

**Comment by BioCookieYT** [comment]
Hi again,
I reworked the cutter design a bit, could you please try out the new Beta6 and see how it goes now?
Thanks

**Comment by Tutankamon00** [comment]
> Hi again, I reworked the cutter design a bit, could you please try out the new Beta6 and see how it goes now? Thanks

New Cutter Arm and Servo Arm for beta6 are compatible with beta5? i have ercf V1 with binky
