### ISSUE TITLE
Macro CUTTER_ACTION called recursively

### ISSUE THREAD

**Issue by pmyrie** [kevinakasam/ERCF_Filament_Cutter#9]
hi, after updating happy-hare to 2.4 every time theh cutter action is call i get,

An issue with the MMU has been detected whilst out of a print
Reason: Error running _MMU_POST_UNLOAD: Macro CUTTER_ACTION called recursively.

**Comment by BioCookieYT** [comment]
Hi, 
gonna find a solution ASAP. Please use HHv2.3 if possible

**Comment by Raabi91** [comment]
> hi, after updating happy-hare to 2.4 every time theh cutter action is call i get,
> 
> An issue with the MMU has been detected whilst out of a print Reason: Error running _MMU_POST_UNLOAD: Macro CUTTER_ACTION called recursively.

please upload you klipper log

**Comment by pmyrie** [comment]
Hi sorry for the delay.

[klippy.log](https://github.com/kevinakasam/ERCF_Filament_Cutter/files/14058736/klippy.log)

**Comment by Tutankamon00** [comment]
Any news? because of this i 'am unable to use ercf, it go in pause and not resume 
![immagine](https://github.com/kevinakasam/ERCF_Filament_Cutter/assets/142754987/258dc0bc-aa19-4b6c-b4f7-d11ac48df715)

**Comment by moggieuk** [comment]
Kevin,  the issue is that `MMU_EJECT` should not be called from within the `_MMU_POST_UNLOAD` macro because that will cause the recursive callback (yes, it just happened to work previously but should not have. lol).

The fix is to replace `MMU_EJECT` with `_MMU_STEP_UNLOAD_GATE`

So that the individual step of unloading the gate is called, not the whole unload sequence.

So I'd recommend:
```
# New Cutter Action Macro - thanks to xF4m3
[gcode_macro CUTTER_Action]
description: Set Servo in the close position. Doesn't work properly yet.
gcode:
    {% set cutvar = printer["gcode_macro _CUT_VAR"] %}
    
    CUTTER_OPEN
    MMU_TEST_MOVE MOVE={cutvar.feed_length + cutvar.cut_length}
    {% for i in range(cutvar.cut_amount) %}
      CUTTER_CLOSE
      CUTTER_OPEN
    {% endfor %}
    MMU_TEST_MOVE MOVE=-1
    CUTTER_CLOSE
    
   _MMU_STEP_SET_FILAMENT STATE=1 
   _MMU_STEP_UNLOAD_GATE
   
    M400
    G4 P0
    ```

**Comment by Tutankamon00** [comment]
I tried the Moggieuk solution and work perfect, thank you :)

**Comment by BioCookieYT** [comment]
> Kevin, the issue is that `MMU_EJECT` should not be called from within the `_MMU_POST_UNLOAD` macro because that will cause the recursive callback (yes, it just happened to work previously but should not have. lol).
> 
> The fix is to replace `MMU_EJECT` with `_MMU_STEP_UNLOAD_GATE`
> 
> So that the individual step of unloading the gate is called, not the whole unload sequence.
> 
> So I'd recommend:
> 
> ```
> # New Cutter Action Macro - thanks to xF4m3
> [gcode_macro CUTTER_Action]
> description: Set Servo in the close position. Doesn't work properly yet.
> gcode:
>     {% set cutvar = printer["gcode_macro _CUT_VAR"] %}
>     
>     CUTTER_OPEN
>     MMU_TEST_MOVE MOVE={cutvar.feed_length + cutvar.cut_length}
>     {% for i in range(cutvar.cut_amount) %}
>       CUTTER_CLOSE
>       CUTTER_OPEN
>     {% endfor %}
>     MMU_TEST_MOVE MOVE=-1
>     CUTTER_CLOSE
>     
>    _MMU_STEP_SET_FILAMENT STATE=1 
>    _MMU_STEP_UNLOAD_GATE
>    
>     M400
>     G4 P0
>     ```
> ```

Thank you so much for helping out! I update the Readme in a bit.
